---
- name: Add mappings to /etc/hosts
  blockinfile:
    path: /etc/hosts
    block: |
      {{ item.ip }} {{ item.namelong }} {{ item.nameshort }}
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.nameshort }}"
  with_items:
  - { ip: 192.168.17.9, namelong: vg-snort-01.local, nameshort: vg-snort-01 }
  - { ip: 192.168.17.10, namelong: vg-snort-02.local, nameshort: vg-snort-02 }
  - { ip: 192.168.17.11, namelong: vg-snort-03.local, nameshort: vg-snort-03 }
  when: add_host_entries
