---
# handlers file for common
- name: restart snort
  service:
    name: snort
    state: restarted
  become: true

- name: restart snortd
  service:
    name: snortd
    state: restarted
  become: true
