---
- name: "Boot all hosts"
  gather_facts: true
  hosts:  all
  become: yes
  vars:
    add_host_entries: true
    add_resolv_entries: true
  pre_tasks:
  - name: "Setting hostname"
    shell: "hostnamectl set-hostname {{ inventory_hostname }}"
  roles:
    - common
- name: "Install snort"
  gather_facts: true
  hosts:  vg-snort-01
  become: yes
  roles:
    - snort
- name: "Install snort"
  gather_facts: true
  hosts:  vg-snort-02
  become: yes
  vars:
    PKG_CONFIG_PATH: "/usr/local/lib64/pkgconfig:/usr/local/lib/pkgconfig:"
  roles:
    - snort
- name: "Install snort"
  gather_facts: true
  hosts:  vg-snort-03
  become: yes
  roles:
    - snort
