---
- name: "ansible_os_family"
  debug:
   msg: "{{ hostvars[inventory_hostname].ansible_os_family }}"

- name: "ansible_distribution"
  debug:
   msg: "{{ hostvars[inventory_hostname].ansible_distribution }}"

- name: "ansible_distribution_major_version"
  debug:
   msg: "{{ hostvars[inventory_hostname].ansible_distribution_major_version }}"

- name: "ansible_distribution_release"
  debug:
   msg: "{{ hostvars[inventory_hostname].ansible_distribution_release }}"

- name: "ansible_distribution_version"
  debug:
   msg: "{{ hostvars[inventory_hostname].ansible_distribution_version }}"

- name: "Add ubuntu snort"
  include_tasks: snort_ubuntu1904.yml
  when: " ansible_os_family == 'Debian' and ansible_distribution == 'Ubuntu' and ansible_distribution_version == '19.04' "


- name: "Add centos snort"
  include_tasks: snort_centos80.yml
  when: " ansible_os_family == 'RedHat' and ansible_distribution == 'CentOS' and ansible_distribution_version == '8.0' "

- name: "Add fedora snort"
  include_tasks: snort_fedora.yml
  when: " ansible_os_family == 'RedHat' and ansible_distribution in ['Fedora'] "

- name: "Add BSD snort"
  include_tasks: snort_fedora.yml
  when: " ansible_os_family == 'BSD' and ansible_distribution in ['Fedora'] "
